<script lang="ts">
  const dataSources = [
    {
      text: 'I built the same identical app in every framework, and then benchmarked them. You can view the source and results for these in',
      link: { text: 'framework-benchmarks', url: 'https://github.com/Lissy93/framework-benchmarks' }
    },
    {
      text: 'I then augment the results with live usage stats for each framework, generated by analysing their package/bundle composition and fetching data from their repos, NPM and other locations.'
    },
    {
      text: 'I also built real-world apps in each framework (many of which serve over 1M annual users), which gave me context to create the qualitative data for each framework'
    },
    {
      text: 'Finally, we embed or link to additional info about each framework, on their official sources (docs, website, github, etc) for more context and further reading'
    }
  ];
</script>

<section class="about-section">
  <div class="section-content">
    <h2>How did we get this data?</h2>
    <ul>
      {#each dataSources as source}
        <li>
          {source.text}
          {#if source.link}
            <a href={source.link.url} target="_blank" rel="noopener noreferrer">{source.link.text}</a>.
          {/if}
        </li>
      {/each}
    </ul>
  </div>
</section>

<style lang="scss">
  .about-section {
    padding: 0;
    animation: fadeInUp 0.6s cubic-bezier(0.4, 0, 0.2, 1) backwards;
    max-width: 1200px;
    margin: 0 auto;

    .section-content {
      background: var(--surface-secondary);
      border: 1px solid var(--border-primary);
      border-radius: var(--radius-lg);
      padding: var(--gap-2xl);
      transition: all var(--transition-normal);

      &:hover {
        box-shadow: var(--shadow-md);
      }
    }

    h2 {
      font-size: var(--font-2xl);
      font-weight: 700;
      color: var(--text-primary);
      margin: 0 0 var(--gap-lg) 0;
      letter-spacing: -0.02em;
    }

    ul {
      list-style: none;
      padding: 0;
      margin: 0;
      display: flex;
      flex-direction: column;
      gap: var(--gap-md);
    }

    li {
      position: relative;
      padding-left: var(--gap-lg);
      font-size: var(--font-base);
      line-height: 1.7;
      color: var(--text-secondary);

      &::before {
        content: '→';
        position: absolute;
        left: 0;
        color: var(--accent-primary);
        font-weight: 700;
      }
    }

    a {
      text-decoration: none;
      font-weight: 600;
      transition: all var(--transition-normal);
      border-bottom: 1px solid transparent;

      &:hover {
        color: var(--accent-gradient);
        border-bottom-color: var(--accent-gradient);
      }
    }
  }

  @keyframes fadeInUp {
    from {
      opacity: 0;
      transform: translateY(20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  @media (max-width: 768px) {
    .about-section {
      h2 {
        font-size: var(--font-xl);
      }

      .section-content {
        padding: var(--gap-lg);
      }
    }
  }
</style>
