<script lang="ts">
  const dataSources = [
    {
      text: 'I built the same identical app in every framework, and then benchmarked them. You can view the source and results for these in',
      link: { text: 'framework-benchmarks', url: 'https://github.com/Lissy93/framework-benchmarks' }
    },
    {
      text: 'I then augment the results with live usage stats for each framework, generated by analysing their package/bundle composition and fetching data from their repos, NPM and other locations.'
    },
    {
      text: 'I also built real-world apps in each framework (many of which serve over 1M annual users), which gave me context to create the qualitative data for each framework'
    },
    {
      text: 'Finally, we embed or link to additional info about each framework, on their official sources (docs, website, github, etc) for more context and further reading'
    }
  ];
</script>

<section class="about-section">
  <div class="section-content">
    <h2>How did we get this data?</h2>
    <ul>
      {#each dataSources as source}
        <li>
          {source.text}
          {#if source.link}
            <a href={source.link.url} target="_blank" rel="noopener noreferrer">{source.link.text}</a>.
          {/if}
        </li>
      {/each}
    </ul>
  </div>
</section>

<style lang="scss">
  @import './about-shared.scss';
</style>
